-- Table: election_sentiment
-- Purpose: Store sentiment analysis results for the 2026 TN Election

CREATE TABLE IF NOT EXISTS election_sentiment (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    platform TEXT,          -- 'twitter', 'youtube'
    handle TEXT,            -- User handle/channel name
    raw_content TEXT,       -- The original post/comment
    sentiment_score FLOAT,  -- -1 to 1 (generated by IndicBERT)
    political_lean TEXT,    -- 'DMK', 'AIADMK', 'TVK', 'NTK', 'Neutral'
    district TEXT,          -- If identifiable (e.g., 'Salem', 'Madurai')
    metadata JSONB DEFAULT '{}'::jsonb -- Views, likes, or 'bot_flag'
);

-- Enable Row Level Security
ALTER TABLE election_sentiment ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable read access for all users" ON election_sentiment
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated app only" ON election_sentiment
    FOR INSERT WITH CHECK (true); -- Adjust this based on your specific auth requirements

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_sentiment_political_lean ON election_sentiment(political_lean);
CREATE INDEX IF NOT EXISTS idx_sentiment_platform ON election_sentiment(platform);
CREATE INDEX IF NOT EXISTS idx_sentiment_district ON election_sentiment(district);
